# Generated by Django 3.2.3 on 2021-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('cloud', 'Cloud')], max_length=150)),
                ('etat', models.CharField(choices=[('active', 'Activé'), ('nonactive', 'Pas encore activé')], max_length=150)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
