# Generated by Django 3.2.3 on 2021-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
